---

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ common_packages }}"


- name: Ensure group ssh exists
  group:
    name: ssh
    state: present
    system: true

- name: adding admin user to group ssh
  user:
    name: "{{ ansible_user }}"
    groups: ssh
    append: yes

- name: Copy fail2ban conf
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: common_restart_fail2ban

- name: Set authorized key for user admin copying it from current user
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ ansible_ssh_public_key_file }}"

- name: Copy SSH server conf
  copy:
    src: custom_config.conf
    dest: /etc/ssh/sshd_config.d/custom_config.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: common_restart_sshserver

- name: Allow connections on 22 port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    jump: ACCEPT
  notify: common_run_iptables_save
  when: ssh_network is not defined

- name: Allow connections on 22 port from allowed nets
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    source: "{{ ssh_network }}"
    jump: ACCEPT
  notify: common_run_iptables_save
  when: ssh_network is defined

- name: Allow established and related traffic in input
  iptables:
    chain: INPUT
    ctstate:
      - ESTABLISHED
      - RELATED
    jump: ACCEPT
  notify: common_run_iptables_save

- name: Allow established and related traffic in forward
  iptables:
    chain: FORWARD
    ctstate:
      - ESTABLISHED
      - RELATED
    jump: ACCEPT
  notify: common_run_iptables_save

- name: policy input ipv4
  iptables:
    chain: INPUT
    policy: DROP
  notify: common_run_iptables_save

- name: policy forward ipv4
  iptables:
    chain: FORWARD
    policy: DROP
  notify: common_run_iptables_save

- name: policy output ipv4
  iptables:
    chain: OUTPUT
    policy: ACCEPT
  notify: common_run_iptables_save

- name: policy input ipv6
  iptables:
    ip_version: ipv6
    chain: INPUT
    policy: DROP
  notify: common_run_iptables_save

- name: policy forward ipv6
  iptables:
    ip_version: ipv6
    chain: FORWARD
    policy: DROP
  notify: common_run_iptables_save

- name: policy output ipv6
  iptables:
    ip_version: ipv6
    chain: OUTPUT
    policy: DROP
  notify: common_run_iptables_save

- name: accept input to lo
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  notify: common_run_iptables_save

- name: reject input to lo that does not arrive from local
  iptables:
    chain: INPUT
    in_interface: ! lo
    jump: REJECT
    destination: 127.0.0.0/8
  notify: common_run_iptables_save

- name: Ensure group ssh exists
  group:
    name: ssh
    state: present
    system: true

- name: Ensure group snapshot exists
  group:
    name: snapshot
    state: present
    system: true

- name: Add the user snapshot
  user:
    name: snapshot
    group: snapshot
    shell: /bin/bash
    groups: ssh
    system: true

- name: Set authorized key for user snapshot copying it from current user
  ansible.posix.authorized_key:
    user: snapshot
    state: present
    key: "{{ snapshot_public_key }}"

- name: Copy sudo snapshot config file
  copy:
    src: snapshot
    dest: /etc/sudoers.d/snapshot
    owner: root
    group: root
    mode: 640

- name: Add other users
  user:
    name: "{{ item }}"
    group: users
    shell: /bin/bash
    system: false
  loop: "{{ other_users }}"
  when: other_users is defined

- name: Install common additional packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ common_additional_packages }}"
  when:  common_additional_packages is defined

- name: Run custom additional commands
  shell: "{{ item }}"
  loop: "{{ common_custom_commands }}"
  when:  common_custom_commands is defined


