---
- name: common_run_iptables_save
  ping: {}
  notify: run_iptables4_save 
  notify: run_iptables6_save 
    
- name: common_run_iptables4_save
  shell : "/usr/sbin/iptables-save > /etc/iptables/rules.v4"
  become: yes
  become_user: root 

- name: common_run_iptables6_save
  shell : "/usr/sbin/ip6tables-save > /etc/iptables/rules.v6"
  become: yes
  become_user: root 

- name: common_restart_sshserver
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

- name: common_restart_fail2ban
  systemd:
    state: restarted
    daemon_reload: yes
    name: fail2ban
